# SPDX-FileCopyrightText: 2024 Ali Sajid Imami
#
# SPDX-License-Identifier: CC0-1.0

indent_type = "Spaces"
indent_width = 4
column_width = 100
quote_style = "AutoPreferDouble"
no_call_parentheses = false
